question_data = [
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In Terraria, you can craft the Cell Phone pre-hardmode.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"Watch_Dogs 2 is a prequel.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.","correct_answer":"True","incorrect_answers":["False"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick Studios&quot;.","correct_answer":"False","incorrect_answers":["True"]},
    {"category":"Entertainment: Video Games","type":"boolean","difficulty":"easy","question":"In &quot;Space Station 13&quot;,  the station has a clown aboard it.","correct_answer":"True","incorrect_answers":["False"]}]